version: "3.1"

services:
  zoo:
    image: zookeeper
    restart: on-failure
    hostname: zoo
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181

  rabbitmq:
    image: rabbitmq:3.8.3-alpine

  orchestrator:
    image: orchestrator:latest
    build:
      context: ./orchestrator
    command: sh -c "sleep 45 && python orchestrator.py"
    ports:
      - "80:5000"
    depends_on:
      - rabbitmq
      - zoo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure
